export type employeeType = {
  id?: number;
  nationalId?: string;
  englishName?: string;
  arabicName?: string;
  mobileNumber?: string;
  email?: string;
  englishAddress?: string;
  arabicAddress?: string;
  jobTitle?: string;
  joiningDate?: Date;
  endDate?: Date;
  allowedBalance?: number;
  remainingBalance?: number;
  billable?: boolean;
  isDisabled?: boolean;
  team?: string[];
  fulltime?: boolean;
  isResigned?: boolean;
};
